package DAO;

import java.sql.*;
//import java.util.ArrayList;
//import java.util.List;

import Model.Account;
import Util.ConnectionUtil;

public class AccountDAO {
   
    /**
     * The account_id should be automatically generated by the sql database if it is not provided because it was
     * 
     * ### Account
        account_id integer primary key auto_increment,
        username varchar(255),
        password varchar(255)
     * 
     */ 
    public Account insertNewAccount(Account newAccount){
        Connection connection = ConnectionUtil.getConnection();
        try {
            // assuming database automatically generate a primary key.
            String sql = "INSERT INTO account(username, password) VALUES (?,?);" ;
            PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            // preparedStatement's setString method 
            preparedStatement.setString(1, newAccount.getUsername());
            preparedStatement.setString(2, newAccount.getPassword());

            preparedStatement.executeUpdate();
            ResultSet pkeyResultSet = preparedStatement.getGeneratedKeys();
            if(pkeyResultSet.next()){
                int generated_newAccount_id = (int) pkeyResultSet.getLong(1);
                return new Account(generated_newAccount_id, newAccount.getUsername(), newAccount.getPassword());
            }
            
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return null;
    }

    public Account loginIntoAccount(Account loginAccount){
        Connection connection = ConnectionUtil.getConnection();
        try {
            String sql = "SELECT * FROM account WHERE username = ? AND password = ?;" ;
            PreparedStatement preparedStatement = connection.prepareStatement(sql);

            preparedStatement.setString(1, loginAccount.getUsername());
            preparedStatement.setString(2, loginAccount.getPassword());

            ResultSet rs = preparedStatement.executeQuery();

            while(rs.next()){
                Account logedAccount = new Account(rs.getInt("account_id"), 
                            rs.getString("username"), 
                            rs.getString("password"));
            return logedAccount;
            }

        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return null;
    }
    
}
