package DAO;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

import Model.Account;
import Util.ConnectionUtil;

public class AccountDAO {
    /**
     * public List<Author> getAllAuthors(){
        Connection connection = ConnectionUtil.getConnection();
        List<Author> authors = new ArrayList<>();
        try {
            //Write SQL logic here
            String sql = "select * from Author;";
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            ResultSet rs = preparedStatement.executeQuery();
            while(rs.next()){
                Author author = new Author(rs.getInt("id"), rs.getString("name"));
                authors.add(author);
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return authors;
    }
    */

    /**
     * ? The account_id should be automatically generated by the sql database if it is not provided because it was
     * 
     * ### Account
        account_id integer primary key auto_increment,
        username varchar(255),
        password varchar(255)
     * 
     */ 
    public Account insertNewAccount(Account newAccount){
        Connection connection = ConnectionUtil.getConnection();
        try {
            // ? Database may automatically generate a primary key.
            String sql = "insert into Account values (?,?);" ;
            PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

            // preparedStatement's setString method 
            preparedStatement.setString(1, newAccount.getUsername());
            preparedStatement.setString(2, newAccount.getPassword());

            preparedStatement.executeUpdate();
            ResultSet pkeyResultSet = preparedStatement.getGeneratedKeys();
            if(pkeyResultSet.next()){
                int generated_newAccount_id = (int) pkeyResultSet.getLong(1);
                return new Account(generated_newAccount_id, newAccount.getUsername(),newAccount.getPassword());
            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        return null;
    }
    
}
